### ISSUE TITLE
Possible error with regex and/or output regarding charset

### ISSUE THREAD

**Issue by jamestalmage** [thlorenz/convert-source-map#13]
The current regex only recognizes charsets with a `:` separator (i.e. `charset:utf-8`), form what I can tell from [MDN](https://developer.mozilla.org/en-US/docs/Web/HTTP/data_URIs) and [Wikipedia](http://en.wikipedia.org/wiki/Data_URI_scheme) the correct form uses an `=` separator (`charset=utf-8`). Right or wrong, I am seeing plenty of tools producing it with the `=` ([google search](https://www.google.com/webhp?q=sourcemappingurl%3Ddata:application%2Fjson%3Bcharset%3Dutf-8))

**Comment by thlorenz** [comment]
Please open a PR to fix this.

**Comment by jamestalmage** [comment]
Do you want to continue to support the `:` character? After searching a bit, I am only seeing this and https://github.com/thlorenz/inline-source-map using the `:` character. My thought would be to continue reading files that have the `:` character for now, start outputting with `=`, and potentially drop support for reading the old way down the road. Your call.

**Comment by thlorenz** [comment]
> continue reading files that have the : character for now

sounds good.

If with time we see almost no cases of `:` we can remove it in a later release although that's not very crucial.

**Comment by jamestalmage** [comment]
done

**Comment by jamestalmage** [comment]
Fixed in 94d69bdb3d5606b79c34f9db7171d65c6f2151cc
