### ISSUE TITLE
CSS support?

### ISSUE THREAD

**Issue by dominicbarnes** [thlorenz/convert-source-map#15]
Starting to mess around with source-maps for duo, and while using this lib I couldn't find any way to support CSS source-maps. In particular, the comment format is _slightly_ different:

```css
/*# sourceMappingURL=... */
```

vs

```js
//# sourceMappingURL=...
```

**Comment by thlorenz** [comment]
PRs welcome to make that work. Please make sure to add tests.

**Comment by dominicbarnes** [comment]
Roger that :)

**Comment by thlorenz** [comment]
Closing for now just PR whenever you have time ;)
