### ISSUE TITLE
__defineGetter__ does not work in IE9

### ISSUE THREAD

**Issue by hipertracker** [thlorenz/convert-source-map#23]
I cannot use this code in IE9 because [it uses `__defineGetter__`](https://github.com/thlorenz/convert-source-map/search?utf8=%E2%9C%93&q=__defineGetter__) instead of [`Object.defineProperty`](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Object/defineProperty).

**Comment by thlorenz** [comment]
Could you please provide a PR that changes that?
Also please verify that this works in all the latest browsers.
Thanks.

**Comment by hipertracker** [comment]
What's PR? It works in Chrome. It does not work in IE9. I use Babel, and Babel uses convert-source-map.

**Comment by hipertracker** [comment]
`__defineGetter__` is

Non-standard
**This feature is non-standard and is not on a standards track. Do not use it on production sites facing the Web: it will not work for every user. There may also be large incompatibilities between implementations and the behaviour may change in the future.**

Deprecated
This feature has been removed from the Web standards. Though some browsers may still support it, it is in the process of being dropped. Do not use it in old or new projects. Pages or Web apps using it may break at any time.

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/__defineGetter__
