### ISSUE TITLE
Convert source map doesn't recognize charset after content type

### ISSUE THREAD

**Issue by playpauseandstop** [thlorenz/convert-source-map#26]
After browserify updated to 10.2.0 and start using browser-pack ^5.0.0, exorcist cannot understand browserify source maps, as they now used charset definition after content type.

More info in https://github.com/substack/node-browserify/issues/1264

**Comment by thlorenz** [comment]
Do you mind providing a PR that fixes this and shows in an added test what it addresses?
Thanks.

**Comment by playpauseandstop** [comment]
It would be tricky, but I'll try

**Comment by playpauseandstop** [comment]
Just understood that this bug request is invalid, nothing wrong with convert-source-map, as it supports charset, but mold-source-map depends on old convert-source-map, so exorcist won't work well with latest browserify.

Fixed this as ``invalid``. Sorry
