### ISSUE TITLE
SourceMappingURL causing failure on Safari

### ISSUE THREAD

**Issue by AStoker** [thlorenz/convert-source-map#31]
I've been all over the interwebz trying to track down what's going on here.  
It appears that there is an issue that only crops up on Safari where the sourceMappingURL is telling Safari to get a map file that doesn't exist.  
References:  
- https://github.com/babel/babel/issues/2317
- https://github.com/jspm/jspm-cli/issues/1003  

The troubled line is on ln 7.
``` javascript
var mapFileCommentRx =
  // //# sourceMappingURL=foo.js.map                       
  /(?:\/\/[@#][ \t]+sourceMappingURL=([^\s'"]+?)[ \t]*$)|(?:\/\*[@#][ \t]+sourceMappingURL=([^\*]+?)[ \t]*(?:\*\/){1}[ \t]*$)/mg
```
That ```// //# sourceMappingURL=foo.js.map``` is what's killing Safari. Everything works fine if that line is removed, and that seems to be what people are having to do in order to get up and running.

**Comment by thlorenz** [comment]
Don't entirely understand your issue. This module helps to remove a sourcemap or convert it. What needs to be done here related to your problem?

**Comment by AStoker** [comment]
What's happening is when this module is used, in Safari, the source mapping url that you have commented out (I'm assuming you're leaving it there as a reference for how it works) is actually being evaluated. And therefore, it is looking for a source map file title `foo.js.map` which doesn't exist. 
So, does that comment need to be there? Is there another way to leave the comment in without having it cause Safari to start looking for the file?

It looks like you have the same thing said twice in comments:  
``` javascript
var mapFileCommentRx =
  // //# sourceMappingURL=foo.js.map                       /*# sourceMappingURL=foo.js.map */
  /(?:\/\/[@#][ \t]+sourceMappingURL=([^\s'"]+?)[ \t]*$)|(?:\/\*[@#][ \t]+sourceMappingURL=([^\*]+?)[ \t]*(?:\*\/){1}[ \t]*$)/mg

```
You have the source map url in a double slash comment, and the multi line comment.

**Comment by michaelprescott** [comment]
This is certainly not a solution, but an ugly, quick work-around in case you're tired of seeing the error in Safari, and don't want to change the code or wait on the fix to make it through to your libraries, such as jspm:

#!/bin/bash
# patch-babel-core.sh
# add resource till fix arrives 
touch ./src/client/jspm_packages/npm/babel-core\@5.8.30/foo.js.map

#!/bin/bash
# unpatch-babel-core.sh
# TODO: remove resource after fix arrives 
rm ./src/client/jspm_packages/npm/babel-core\@5.8.30/foo.js.map

**Comment by thlorenz** [comment]
Ah wow, that's a Safari bug you should probably report @AStoker.
I'm open to a PR that slightly changes the reference comment to work around that.

**Comment by AStoker** [comment]
I'll readily admit that this is a little above my knowledge with source maps and the such. But do we need that line (both parts) that's commented out looking for a file called `foo.js.map`? Granted, it might be a bug that still needs to be reported. But in the interim, is that line needed?

**Comment by thlorenz** [comment]
Yes I'd like to keep that line to be able to understand the regex, but if you provide a PR that slightly changes it in order to not trip up Safari I'm gonna accept that.

**Comment by AStoker** [comment]
If you only need the line to understand the regex, would you mind if I just stripped out the first example? That's the only one that's causing issues in Safari. So as a result, it would just have the comment:  
 ```/*# sourceMappingURL=foo.js.map*/```

**Comment by thlorenz** [comment]
Just change it slightly to not trip up Safari, but don't rip it out entirely please.

**Comment by AStoker** [comment]
Is there still something wrong with the changes I made? Can this be merged?

**Comment by cellvia** [comment]
this is causing problems with the npm package devtool,  causing debugging w/ babel to crash... any chance for this to be addressed?

please see https://github.com/Jam3/devtool/issues/74
