### ISSUE TITLE
Fail toComment with included content.

### ISSUE THREAD

**Issue by elfet** [thlorenz/convert-source-map#33]
I use mozilla/source-map for generating source maps. Then i add source content, convert to comment fails.

``` js
    var output = node.toStringWithSourceMap();
    output.map.setSourceContent(file, data); // If this

    var map = convert.fromJSON(output.map.toString());
    callback(null, output.code + '\n' + map.toComment()); // Fails here
```

If i comment this line `output.map.setSourceContent(file, data);` all ok. (but no source maps in browser).

Can you help me with this? Thanks.

**Comment by Delagen** [comment]
if map is object use
```
 var map = convert.fromObject(output.map);
```
