### ISSUE TITLE
Error when running angular2-seed build process??

### ISSUE THREAD

**Issue by lmessinger** [thlorenz/convert-source-map#44]
Error: /home/liorm/devcode/servo-admin/src/client/node_modules/convert-source-map/test/fixtures/map-file-comment-double-slash.css:14:1: Unknown word

//# sourceMappingURL=map-file-comment.css.map
^
any ideas, anyone ?

:-o

**Comment by phated** [comment]
I'm not sure why your angular2-seed was trying to read a file from inside our test folder, but it shouldn't be. You might need to change things about that project.
