### ISSUE TITLE
Support non-base64 encoded json?

### ISSUE THREAD

**Issue by lydell** [thlorenz/convert-source-map#48]
convert-source-map currently supports comments like these:

```
/*# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJtYXBwaW5ncyI6IkFBQUEiLCJzb3VyY2VzIjpbInN1Y2Nlc3MuY3NzIl0sIm5hbWVzIjpbXX0= */
```

However, those don’t _have_ to be base64 encoded!

```
/*# sourceMappingURL=data:application/json,{"version":3,"mappings":"AAAA","sources":["success.css"],"names":[]} */
```

Here is the above example again, after running `encodeURIComponent` on it:

```
/*# sourceMappingURL=data:application/json,%7B%22version%22%3A3%2C%22mappings%22%3A%22AAAA%22%2C%22sources%22%3A%5B%22success.css%22%5D%2C%22names%22%3A%5B%5D%7D */
```
### Do any browsers support this?

I created a test to find out: https://gist.github.com/lydell/3c3375e7a9dc1265fe71474a9e098077

| encoding | Firefox | Chrome | Safari | Edge |
| --- | --- | --- | --- | --- |
| base64 | yes | yes | yes | yes |
| encodeURIComponent | yes | yes | yes | no |
| nothing | yes | no | no | no |
### Do any tools support this?
- [PostCSS can consume such source maps](https://github.com/postcss/postcss/blob/c03afd177544c37fef450fa7efcb9642fa0e6db3/lib/previous-map.es6#L71-L93).
- [source-map-resolve can consume such source maps](https://github.com/lydell/source-map-resolve/blob/663ad74f07aab1d5ef44942fd9c4df91cee5e687/lib/source-map-resolve-node.js#L70-L102).
### Do any tools _output_ this?

I don’t know. Perhaps @ai does, since he added support for consuming it in PostCSS. (I added consumption support in source-map-resolve because I noticed that PostCSS had.)
### Should convert-source-map support it?

Well, it’s not hard.
- `data:mime-type;parameters;base64,...` → base64
- `data:mime-type;parameters,...` (not ending with `;base64`) → decodeURIComponent

I just don’t know how it fits into the API.

Thanks for reading :)

**Comment by ai** [comment]
@lydell PostCSS outputs only `base64` source maps https://github.com/postcss/postcss/blob/master/lib/map-generator.es6#L128-L129

But we added non-base64 source map support, because some tool uses it. Maybe Less or Stylus? (Sorry, it was year ago)

**Comment by lydell** [comment]
> PostCSS outputs only base64 source maps

Sorry, I didn’t mean to imply anything else, my wording was just bad :) I’ve edited the issue description to be more clear about this.

**Comment by thlorenz** [comment]
@lydell not sure if this is still a priority for you, but PR with a change along with some tests.
Obviously make sure this won't break anything else.

However I'm not a huge fan of magic, so I wouldn't want it to decode on it's own account.
I believe either adding a method `fromEncodedURIComment` or similar might be better.
So you'd get the comment out of the source and then pass the result there to have it decoded.

On the other hand most people could also just decode themselves, so if it's just a one-liner it doesn't belong here. If it's more complex however and more related to how we handle source maps comments then it may belong here.

**Comment by lydell** [comment]
Let’s close this until somebody needs it.
