### ISSUE TITLE
Rogue sourceMappingURL comment trips up devtools

### ISSUE THREAD

**Issue by dongryphon** [thlorenz/convert-source-map#50]
See https://github.com/thlorenz/convert-source-map/blob/master/index.js#L8
```
  //Example (Extra space between slashes added to solve Safari bug. Exclude space in production):
  //     / /# sourceMappingURL=foo.js.map           /*# sourceMappingURL=foo.js.map */
  /(?:\/\/[@#][ \t]+sourceMappingURL=([^\s'"]+?)[ \t]*$)|(?:\/\*[@#][ \t]+sourceMappingURL=([^\*]+?)[ \t]*(?:\*\/){1}[ \t]*$)/mg
```
The comment is generating a 404 in `devtool` and it is shutting down immediately when trying to debug.

It would be great if you change the comment so it doesn't match the regex and make the debugger thing there is a `foo.js.map` file :)

Thanks!

See also https://github.com/evanw/node-source-map-support/issues/156 for the same report

**Comment by thlorenz** [comment]
Sorry, seems to be a chrome devtools bug.
Why would you open it up anyways unless you're trying to debug this module?

At any rate, nothing we can fix here .. better to file a bug with the chrome people.
