### ISSUE TITLE
source-map file name with query parameter, causes source-map not found

### ISSUE THREAD

**Issue by UncleBill** [thlorenz/convert-source-map#52]
In the javascript file, if `sourceMappingURL` file name has parameter, like:

```javascript
//# sourceMappingURL=foo.min.js.map?hashcode
```
the converter can't find the source map file
https://github.com/danvk/source-map-explorer/issues/46

**Comment by thlorenz** [comment]
That's not a valid source map. You have to adhere to the [spec](https://docs.google.com/document/d/1U1RGAehQwRypUTovF1KRlpiOFze0b-_2gc6fAH0KY0k/edit) and I'm not aware that query params are supported.

**Comment by UncleBill** [comment]
As the spec saying, I think it's valid.
>![image](https://cloud.githubusercontent.com/assets/1141198/24987802/6b9157aa-2034-11e7-9514-d1a1cd7c3b5c.png)
>https://docs.google.com/document/d/1U1RGAehQwRypUTovF1KRlpiOFze0b-_2gc6fAH0KY0k/edit

<code>foo.min.js.map?hashcode</code> should be a valid `url` as:
>![image](https://cloud.githubusercontent.com/assets/1141198/24987959/5fc7befe-2035-11e7-972b-810b914bf765.png)
>https://tools.ietf.org/html/rfc3986#page-16

**Comment by thlorenz** [comment]
In your image it says something along the lines of `?name=...` however yours just has `?hashcode` no `=`.
Yours looks more like a mixture between a filename and a url query.
So I'm still not convinced that it's valid.

Also you're the first that reports this problem, hoping that other @collaborators can chime in.

**Comment by lydell** [comment]
URL parameters without values are perfectly valid.

**Comment by thlorenz** [comment]
OK @lydell thanks.
Seems like we need to fix this then. Anyone wanna take on making the already super complex Regex even more complex? :P
Seriously though, @UncleBill open to PRs that fix it with added tests (and of course without breaking existing tests).

**Comment by phated** [comment]
This will be resolved with https://github.com/thlorenz/convert-source-map/pull/76 because you'll need to pass your own function to read the map and you can strip off the querystring (or use them if you are in the browser!)
