### ISSUE TITLE
Reduce package size

### ISSUE THREAD

**Issue by evilebottnawi** [thlorenz/convert-source-map#54]
Now after `npm i convert-source-map` i get these extra unnecessary directories: `example` and `test`, also `.travis.yml` file. I can do PR :smile:

**Comment by thlorenz** [comment]
They aren't unnecessary if you happen to be offline and try to understand how things work.
Also they aren't that big. Show me that we'd save at least 4K if we remove them, otherwise it's not worth removing.
Thanks.

**Comment by evilebottnawi** [comment]
@thlorenz If each package will save even a few files that are not required for the work of the package, then `node_modules` цill grow that is negatively related to the size of the application, especially when it is important to have as small a `docker` container. Practically for all packages it is good practice to remove such files.

**Comment by evilebottnawi** [comment]
@thlorenz when i use package in `package.json` i almost never need to have files for developers, if I want to work and help, I download the package directly with tests and other information

**Comment by thlorenz** [comment]
You can't download anything if you happen to be offline ;)

I understand your concern, however please show me how much you'd actually save via `npm pack`.
pack it once with and once without removing those files via .npmignore.
Then tell me the difference as a basis of discussion. I doubt that the difference is large enough but we'll see.

**Comment by evilebottnawi** [comment]
@thlorenz 
Before: `12627` byte.
After: `3844` byte.

I think it should be convincingly. About 8Kbyte.

**Comment by thlorenz** [comment]
OK thanks @evilebottnawi prep the PR .. make sure to include in the `.npmignore` all that was in `.gitignore`, i.e. create it via `cat .gitignore > .npmignore` then add tests and examples.

BTW I'm interested what others think about this topic, so I launched a twitter survey: https://twitter.com/thlorenz/status/847802273170432004

**Comment by evilebottnawi** [comment]
@thlorenz Great idea about voting, I'm also interested in how the community considers.

**Comment by phated** [comment]
@thlorenz I wasn't big into this until the gulp team jumped onboard and it brought install times way down (especially on poor speed internet).  We use the `files` property of `package.json` to indicate which files should be included (as opposed to ignored).

**Comment by thlorenz** [comment]
Makes sense @phated. I already agreed to the change, just waiting for @evilebottnawi to provide the PR.

I'll also be more open to that kind of change for my other modules as I can see that the community wants this (right now it's 75% of people not caring about tests or examples to be installed with the package).

**Comment by evilebottnawi** [comment]
Done in https://github.com/thlorenz/convert-source-map/pull/56
