### ISSUE TITLE
sourceMappingURL with non-base64 data URI not supported.

### ISSUE THREAD

**Issue by jdalton** [thlorenz/convert-source-map#59]
```js
convert
  .fromComment('//# sourceMappingURL=data:application/json;charset=utf-8,%7B%22version%22:3,%22sources%22:%5B%22/Users/user/Development/node_modules/xyz/index.js%22%5D,%22names%22:%5B%5D,%22mappings%22:%22AAAA%22%7D')
  .toJSON()
```
Will throw:
```
SyntaxError: Unexpected token � in JSON at position 0
```
The map is:
```json
{"version":3,"sources":["/Users/user/Development/node_modules/xyz/index.js"],"names":[],"mappings":"AAAA"}
```
This effects https://github.com/Microsoft/vscode/issues/35978.

**Comment by lydell** [comment]
https://github.com/thlorenz/convert-source-map/issues/48#issuecomment-292548450

> Let’s close this until somebody needs it.

Guess that time is now.

**Comment by jdalton** [comment]
Worth noting Chrome devs tools in Electron and Chrome 61 with `node --inspect` work with these `data:application/json` style `sourceMappingURL`s.

**Comment by thlorenz** [comment]
Not entirely sure what the fix should be .. hoping someone will provide a PR with a fix that doesn't break any tests to make sure all is still backwards compat.

**Comment by lydell** [comment]
Easy. Just follow [RFC 2397](https://tools.ietf.org/html/rfc2397):

> The [data] URLs are of the form:
>
>     data:[<mediatype>][;base64],<data>
>
> The <mediatype> is an Internet media type specification (with optional parameters.) The appearance of ";base64" means that the data is encoded as base64. Without ";base64", the data (as a sequence of octets) is represented using ASCII encoding for octets inside the range of safe URL characters and using the standard %xx hex encoding of URLs for octets outside that range.  If <mediatype> is omitted, it defaults to text/plain;charset=US-ASCII.  As a shorthand, "text/plain" can be omitted but the charset parameter supplied.

**Comment by thlorenz** [comment]
> Easy. Just follow RFC 2397:

Would love a PR @lydell as I'm not gonna be able to address ATM due to time constraints :)

**Comment by thlorenz** [comment]
Or maybe @jdalton wants to pick it up since this is affecting VSCode ... 
LMK if so, I'll made you collab in the mean time

**Comment by jdalton** [comment]
Rock 🤘 !

If @lydell wants to lead, I can review. Else I can find some time to dig in.

**Comment by lydell** [comment]
@jdalton I guess you need to find that to dig in. I'm just the random guy who links to specs.

**Comment by jdalton** [comment]
Ok so it turns out the vscode issue isn't related to `convert-source-map` though it couldn't hurt to patch this. I haven't forgotten I'm on the hook.
