### ISSUE TITLE
Braking typescript/nyc coverage report

### ISSUE THREAD

**Issue by tsadigovAgmail** [thlorenz/convert-source-map#66]
Came here while debugging my setup. 
I get Error: ENAMETOOLONG: name too long, open '/Users/test/D.../data:application/json;charset=utf-8;base64,eyJ2ZX

Using MACOS

Found out that regex does not match the source map. When removing start of line character it worked.

Example end with this..

(backbone_1["default"].Collection));cov_lp6smvaoa.s[21]++;exports.Collection=Collection;//# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiL1VzZXJzL3Rlc3QvRGVza3RvcC9tYXBseXRpY3MvYXRvbS9MYXllckJhc2UvQ29sbGVjdGlvbi50cyIsInNvdXJjZXMiOlsiL1VzZXJzL3Rlc3QvRGVza3RvcC9tYXBseXRpY3MvYXRvbS9MYXllckJhc2UvQ29sbGVjdGlvbi50cyJdLCJuYW1lcyI6W10sIm1hcHBpbmdzIjoiOzs7Ozs7Ozs7Ozs7Ozs7Ozs7O0FBQ0Esc0RBQWdDO0FBRWhDO0lBQWdDLDhCQUFrQztJQUFsRTs7SUFBcUUsQ0FBQztJQUFELGlCQUFDO0FBQUQsQ0FBQyxBQUF0RSxDQUFnQyxxQkFBUSxDQUFDLFVBQVUsR0FBbUI7QUFBekQsZ0NBQVUiLCJzb3VyY2VzQ29udGVudCI6WyJpbXBvcnQgeyBNb2RlbCwgSU1vZGVsIH0gZnJvbSBcIi4vTW9kZWxcIjtcbmltcG9ydCBCYWNrYm9uZSBmcm9tIFwiYmFja2JvbmVcIjtcblxuZXhwb3J0IGNsYXNzIENvbGxlY3Rpb24gZXh0ZW5kcyBCYWNrYm9uZS5Db2xsZWN0aW9uPE1vZGVsPElNb2RlbD4+IHsgfVxuIl19

**Comment by phated** [comment]
Note in the [SourceMap spec](https://sourcemaps.info/spec.html) it says:
> The generated code may include a line at the end of the source, with the following form:
> `//# sourceMappingURL=<url>`

Which indicates that it must be on its own line at the end of the source file. Please open an issue upstream on the dependency producing invalid source files.
