### ISSUE TITLE
Safe to remove safe-buffer

### ISSUE THREAD

**Issue by jimmywarting** [thlorenz/convert-source-map#70]
bet many have updated their node version already.
Willing to change lowest supported node version to something like LTS and use native `Buffer.from` instead to reduce the size?

Can help you with a PR if you like.

**Comment by phated** [comment]
This minuscule size reduction is likely not worth dropping backwards-compat with older Nodes. Some users might be stuck, so we should land everything patchable before bumping a major. Want to help on some of the open issues?
