### ISSUE TITLE
charset is not supported

### ISSUE THREAD

**Issue by vvakame** [thlorenz/convert-source-map#9]
sourceMappingUrl allows data uri.
https://docs.google.com/document/d/1U1RGAehQwRypUTovF1KRlpiOFze0b-_2gc6fAH0KY0k/edit#heading=h.lmz475t4mvbx

data uri allows contains charset.
http://en.wikipedia.org/wiki/Data_URI_scheme#Format
https://www.ietf.org/rfc/rfc2397.txt

now commentRx is not support it.
https://github.com/thlorenz/convert-source-map/blob/master/index.js#L5

**Comment by dbashford** [comment]
:+1: 

Would be a bit of a challenge give the ordering isn't standard.

**Comment by jmeas** [comment]
@thlorenz, need any help implementing this?

**Comment by thlorenz** [comment]
@jmeas mainly limited bandwidth is preventing me.
PR with tests welcome :)

**Comment by thlorenz** [comment]
Fixed in [inline-source-map PR](https://github.com/thlorenz/inline-source-map/commit/6b5f7ff8ba7fef8b70990295113019b0cd57fb54).
Similar changes would fix it here. Any takers? Really have no time for this myself.

**Comment by thlorenz** [comment]
Also fixed for main regex as part of #11.
Applying this change for mapFileRegex is [pending](https://github.com/thlorenz/convert-source-map/pull/11#issuecomment-75067442)

**Comment by greim** [comment]
> Applying this change for mapFileRegex is pending 

Am I correct in thinking charset actually shouldn't exist in `mapFileRegex` since it's matching a file path rather than a data URI? Or does source map spec allow this somehow?

**Comment by thlorenz** [comment]
Good point, I'm not entirely sure.
I mean you'd still have to communicate what the charset is that's use in the file.
Something to research I guess.

**Comment by greim** [comment]
Yeah. I'm still coming up to speed on source maps after diving into this. If the file is loaded over http then presumably the charset would be in the `content-type` header. If it's coming from the filesystem, it uses utf8 (assuming I'm looking at the right part of the code: https://github.com/thlorenz/convert-source-map/blob/master/index.js#L29).

My inclination at least for now would be to leave it off of `mapFileCommentRx`.
